version: '3'
services:
  db:
    build: 
      context: ./
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - 8282:8080
    depends_on: 
      - db

volumes:
  db_data: